made index page look nicer and added client count pie chart
ethereum/glados pull request #136
Opened 2023-06-17 23:42 UTC by KaydenML

I styled the index page to make it overall look cleaner and i created a pie chart using d3.js libraries to display how many nodes are on the network and which clients they are so trin, fluffy, ultralight, and unknown". I also made it so if the client count is 0 it will not be displayed.

I want to make glados look nicer and im also interested in making more interesting graphs that will display interesing information about the network that i believe would be useful. This has been my first step working with glados through this i have learned new stuff about glados and how alot of the glados framework works which will help me with further implementation 
![Screenshot from 2023-06-17 17-36-20](https://github.com/ethereum/glados/assets/104690535/79fb94c0-b580-41a4-af85-36b4c7460cb6)

2023-06-19 18:15 UTC, pipermerriam commented on glados-web/Cargo.toml
> +rust-version = "1.70.0"
In the future, I would request that you "isolate" these kinds of changes, and put them into a separate pull request.

2023-06-19 18:19 UTC, pipermerriam requested changes

2023-06-19 18:19 UTC, pipermerriam commented on glados-web/src/routes.rs
> +    for model in enr_list {
I believe I'm not going to be able to :+1: this approach.  It has linear runtime complexity with respect to the number of rows that are in the database, which means it will take longer and longer the larger our database grows... and the plan is for the DB to get very big..

This kind of operation can be done using aggregate queries and offloaded to the database itself.  I would encourage you to look into that approach.

2023-06-19 18:20 UTC, pipermerriam commented on glados-web/src/routes.rs
> +    for model in enr_list {
https://www.sea-ql.org/SeaORM/docs/advanced-query/aggregate-function/

2023-06-19 19:44 UTC, KaydenML commented on glados-web/src/routes.rs
> +    for model in enr_list {
Thank you very much for reviewing this and giving me your insights and feedback on this it really helps me to learn and improve myself. Going forward when working I will keep in mind that the data for the database to is going to become very big and store tons of data so when i'm implementing changes I will make it so its able to handle large amounts of data more efficiently and run as fast as possible. Thank you for giving me insights on a better approach to achieve this and I will definitely look into using aggregate queries to be able to handle large amount of data.

2023-06-19 19:45 UTC, KaydenML commented on glados-web/Cargo.toml
> +rust-version = "1.70.0"
Thnak you Piper for taking in the time of your day to be able to review my pull request. Going forward I will try to isolate these kinds of changes into smaller task and make separate pull requests.

2023-06-20 00:11 UTC, KaydenML commented on glados-web/src/routes.rs
> +    for model in enr_list {
Piper i see two ways we can accomplish you goals. The current issue is the record table only store a raw enr. So in order to do a aggregate function I will need to upgrade cartographer and the records table to hold the decoded entries of the enr. For my use case this will be adding a table entry called client but since where already doing it we should put all the enr's into there own entries into the table. Another possible solution would be to make a table with stats for graphs to use. The benefit of this as we got data to insert data into the database we could update the stats instead of calculating the stats from scratch everytime.

Since you recommend me using a aggregation function I will go along with the option one i listed.

2023-06-20 00:43 UTC, KaydenML commented on glados-web/src/routes.rs
> +    for model in enr_list {
never mind i see that the information i am seeking is already in the database under the key_value table

2023-06-30 18:43 UTC, KaydenML commented on glados-web/Cargo.toml
> +rust-version = "1.70.0"
https://github.com/ethereum/glados/pull/137 ok i made a PR if we want to merge it in separate its up to you guys.

2023-07-05 16:41 UTC, pipermerriam commented
with #137 merged you can now rebase this on top of those changes.

2023-07-05 16:46 UTC, pipermerriam commented on glados-web/src/routes.rs
> +                    Func::max(Expr::col(record::Column::Id)),
I don't know how important it is that this get fixed immediately, but IIUC this is equating highest `id` as also being the "latest" ENR record, which is typically going to be true, but has no guarantees of being true. If we encounter an old ENR after recording the latest ENR, then this will end up picking the older ENR record.

I think that this should potentially be preferring the largest `sequence_number` instead.

2023-07-05 16:47 UTC, pipermerriam commented on glados-web/src/routes.rs
> +                        .cast_as(Alias::new("TEXT"))
I'm not very familiar with this API but this has a small "code smell", casting the table to `TEXT` in order to do the comparison.  It seems we should be able to do a direct comparison to the binary value without the cast?

2023-07-05 16:49 UTC, pipermerriam reviewed
Ok, one more piece of homework before this can be merged.  I'd like you to verify that this runs in sub-linear query time.  I see two paths to getting there.

1. Extract the full query that this generates and run it with an `EXPLAIN` to see that it is hitting database indexes on all of it's table queries. 
2. Generate some databases with 100/1000/10000/100000 database records and benchmark this query against them.  You should see non-linear query numbers.

2023-07-05 16:54 UTC, pipermerriam commented on glados-web/templates/index.html
> +<script src="https://d3js.org/d3.v7.min.js"></script>
We should vendor this instead of relying on a 3rd party.

In the `base.html` template you can add two new blocks for "scipts" and "stylesheets"

https://github.com/ethereum/glados/blob/31e1a9d87013a64f504b479049d9d25e55c964ee/glados-web/templates/base.html#L8-L9

Then, I believe that you can do this in a sub-template to add to those blocks.

```
{% block scripts %}
{{ block.super }}
<script src="/static/js/d3.min.js"></script>
{% endblock %}
```

This will allow us to selectively include additional JS/CSS files in specific templates while still loading them in the `<head>` part of the HTML

2023-07-05 16:57 UTC, pipermerriam commented on glados-web/templates/index.html
> +    stroke = innerRadius > 0 ? "none" : "white", // stroke separating widths
This whole script section should also be placed in a `something.js` file and loaded via injection into the `<head>` element as I outlined in a previous comment.

2023-07-05 16:59 UTC, pipermerriam commented on glados-web/templates/index.html
> +
My recommendation would be to modify this script so that it can take these values as an input to a function, that way you don't have to template the full javascript, but rather dump a single rust object to JSON and then pass it into that function to render the pie-chart.

2023-07-08 19:27 UTC, KaydenML commented on glados-web/src/routes.rs
> +                        .cast_as(Alias::new("TEXT"))
I looked into this and when i did the number c in hex equals the column it did not work and removed the cast.

2023-07-09 16:05 UTC, pipermerriam commented on glados-web/src/routes.rs
> +                        .cast_as(Alias::new("TEXT"))
Can you leave a comment here that includes that explanation so that future readers of this code can know why we're using a CAST.

2023-07-09 16:06 UTC, pipermerriam commented on glados-web/templates/index.html
> +   pie_chart_count({{ pie_chart_client_count|json|safe }})
:heart: love this so much more.  thanks for making these changes.

2023-07-09 16:08 UTC, pipermerriam approved these changes
@mrferris will you give this a quick second look?  I still think that this should be benchmarked against a large DB of ENR records with some database EXPLAIN statements to make sure we're hitting database indexes on these queries.

2023-07-10 18:57 UTC, KaydenML commented
hey piper i have done some tests and it runs linear time here's the tests i have ran
db100 : 100 rows returned in “8ms” from 
SELECT COUNT("id") AS "client_count", CAST(ifnull(substr("right_table"."value", 2, 1), 'unknown') AS TEXT) AS "client_name" FROM (SELECT "id" AS "record_id" FROM "record" GROUP BY "node_id" HAVING MAX("sequence_number")) AS "left_table" LEFT JOIN (SELECT "record_id", "value" FROM "key_value" WHERE CAST("key" AS TEXT) = 'c') AS "right_table" ON "left_table"."record_id" = "right_table"."record_id" GROUP BY substr("right_table"."value", 2, 1)


db1000 : 1000 rows returned in “6ms” from 
SELECT COUNT("id") AS "client_count", CAST(ifnull(substr("right_table"."value", 2, 1), 'unknown') AS TEXT) AS "client_name" FROM (SELECT "id" AS "record_id" FROM "record" GROUP BY "node_id" HAVING MAX("sequence_number")) AS "left_table" LEFT JOIN (SELECT "record_id", "value" FROM "key_value" WHERE CAST("key" AS TEXT) = 'c') AS "right_table" ON "left_table"."record_id" = "right_table"."record_id" GROUP BY substr("right_table"."value", 2, 1)


db10000 : 10000 rows returned in “50ms” from 
SELECT COUNT("id") AS "client_count", CAST(ifnull(substr("right_table"."value", 2, 1), 'unknown') AS TEXT) AS "client_name" FROM (SELECT "id" AS "record_id" FROM "record" GROUP BY "node_id" HAVING MAX("sequence_number")) AS "left_table" LEFT JOIN (SELECT "record_id", "value" FROM "key_value" WHERE CAST("key" AS TEXT) = 'c') AS "right_table" ON "left_table"."record_id" = "right_table"."record_id" GROUP BY substr("right_table"."value", 2, 1)


db100000 : 100000 rows returned in “553ms” from 
SELECT COUNT("id") AS "client_count", CAST(ifnull(substr("right_table"."value", 2, 1), 'unknown') AS TEXT) AS "client_name" FROM (SELECT "id" AS "record_id" FROM "record" GROUP BY "node_id" HAVING MAX("sequence_number")) AS "left_table" LEFT JOIN (SELECT "record_id", "value" FROM "key_value" WHERE CAST("key" AS TEXT) = 'c') AS "right_table" ON "left_table"."record_id" = "right_table"."record_id" GROUP BY substr("right_table"."value", 2, 1)














db100t2 : 100 rows returned in “8ms” from 
SELECT COUNT("id") AS "client_count", CAST(ifnull(substr("right_table"."value", 2, 1), 'unknown') AS TEXT) AS "client_name" FROM (SELECT "id" AS "record_id" FROM "record" GROUP BY "node_id" HAVING MAX("sequence_number")) AS "left_table" LEFT JOIN (SELECT "record_id", "value" FROM "key_value" WHERE CAST("key" AS TEXT) = 'c') AS "right_table" ON "left_table"."record_id" = "right_table"."record_id" GROUP BY substr("right_table"."value", 2, 1)


db1000t2 : 1000 rows returned in “6ms” from 
SELECT COUNT("id") AS "client_count", CAST(ifnull(substr("right_table"."value", 2, 1), 'unknown') AS TEXT) AS "client_name" FROM (SELECT "id" AS "record_id" FROM "record" GROUP BY "node_id" HAVING MAX("sequence_number")) AS "left_table" LEFT JOIN (SELECT "record_id", "value" FROM "key_value" WHERE CAST("key" AS TEXT) = 'c') AS "right_table" ON "left_table"."record_id" = "right_table"."record_id" GROUP BY substr("right_table"."value", 2, 1)


db10000t2 : 10000 rows returned in “63ms” from 
SELECT COUNT("id") AS "client_count", CAST(ifnull(substr("right_table"."value", 2, 1), 'unknown') AS TEXT) AS "client_name" FROM (SELECT "id" AS "record_id" FROM "record" GROUP BY "node_id" HAVING MAX("sequence_number")) AS "left_table" LEFT JOIN (SELECT "record_id", "value" FROM "key_value" WHERE CAST("key" AS TEXT) = 'c') AS "right_table" ON "left_table"."record_id" = "right_table"."record_id" GROUP BY substr("right_table"."value", 2, 1)


db100000t2 : 100000 rows returned in “615ms” from 
SELECT COUNT("id") AS "client_count", CAST(ifnull(substr("right_table"."value", 2, 1), 'unknown') AS TEXT) AS "client_name" FROM (SELECT "id" AS "record_id" FROM "record" GROUP BY "node_id" HAVING MAX("sequence_number")) AS "left_table" LEFT JOIN (SELECT "record_id", "value" FROM "key_value" WHERE CAST("key" AS TEXT) = 'c') AS "right_table" ON "left_table"."record_id" = "right_table"."record_id" GROUP BY substr("right_table"."value", 2, 1)

2023-07-12 21:59 UTC, pipermerriam commented
So, your experiment verifies that this runs in **linear** time, which is not what we want.  We want sub-linear because otherwise, as our database of ENR records grows, our query time for the main homepage will also grow at the same rate.

I would recommend using EXPLAIN statements to understand where your query is missing database indices and figure out how to fix those.

2023-07-19 18:04 UTC, KaydenML commented
hey piper i have done some new tests and it runs in sub-linear time. I reran the tests on postgres and found it does run in sublinear time, it seems though that the indexes don't work on sqlite. My old sql statement wasn't compatible with posgres so I had to update it, its function is identical though. 

The indexes work on postgres (sublinear times) but not on sqlite (linear times)

here's the tests i have ran:
- db* is all unknown clients

- db*t2 is half known and half unknown clients




postgresdb100 31m 100rows
SELECT CAST(COUNT(*) AS INT) AS "client_count", CAST(COALESCE(substr(value, 2, 1), 'unknown') AS TEXT) AS "client_name" FROM (SELECT "id" AS "record_id" FROM "record", (SELECT "node_id", MAX("sequence_number") AS "sequence_number" FROM "record" GROUP BY "node_id") AS "max_sequence_number" WHERE ("record"."node_id" = "max_sequence_number"."node_id") AND ("record"."sequence_number" = "max_sequence_number"."sequence_number")) AS "left_table" LEFT JOIN (SELECT "record_id", "value" FROM "key_value" WHERE convert_from(key, 'UTF8') = 'c') AS "right_table" ON "left_table"."record_id" = "right_table"."record_id" GROUP BY substr(value, 2, 1)

postgresdb1000 66m 1000rows
SELECT CAST(COUNT(*) AS INT) AS "client_count", CAST(COALESCE(substr(value, 2, 1), 'unknown') AS TEXT) AS "client_name" FROM (SELECT "id" AS "record_id" FROM "record", (SELECT "node_id", MAX("sequence_number") AS "sequence_number" FROM "record" GROUP BY "node_id") AS "max_sequence_number" WHERE ("record"."node_id" = "max_sequence_number"."node_id") AND ("record"."sequence_number" = "max_sequence_number"."sequence_number")) AS "left_table" LEFT JOIN (SELECT "record_id", "value" FROM "key_value" WHERE convert_from(key, 'UTF8') = 'c') AS "right_table" ON "left_table"."record_id" = "right_table"."record_id" GROUP BY substr(value, 2, 1)

postgresdb10000 81m 10000rows
SELECT CAST(COUNT(*) AS INT) AS "client_count", CAST(COALESCE(substr(value, 2, 1), 'unknown') AS TEXT) AS "client_name" FROM (SELECT "id" AS "record_id" FROM "record", (SELECT "node_id", MAX("sequence_number") AS "sequence_number" FROM "record" GROUP BY "node_id") AS "max_sequence_number" WHERE ("record"."node_id" = "max_sequence_number"."node_id") AND ("record"."sequence_number" = "max_sequence_number"."sequence_number")) AS "left_table" LEFT JOIN (SELECT "record_id", "value" FROM "key_value" WHERE convert_from(key, 'UTF8') = 'c') AS "right_table" ON "left_table"."record_id" = "right_table"."record_id" GROUP BY substr(value, 2, 1)


postgresdb100000 321m 100000rows
SELECT CAST(COUNT(*) AS INT) AS "client_count", CAST(COALESCE(substr(value, 2, 1), 'unknown') AS TEXT) AS "client_name" FROM (SELECT "id" AS "record_id" FROM "record", (SELECT "node_id", MAX("sequence_number") AS "sequence_number" FROM "record" GROUP BY "node_id") AS "max_sequence_number" WHERE ("record"."node_id" = "max_sequence_number"."node_id") AND ("record"."sequence_number" = "max_sequence_number"."sequence_number")) AS "left_table" LEFT JOIN (SELECT "record_id", "value" FROM "key_value" WHERE convert_from(key, 'UTF8') = 'c') AS "right_table" ON "left_table"."record_id" = "right_table"."record_id" GROUP BY substr(value, 2, 1)

postgresdb1000000 2.022m 1000000rows
SELECT CAST(COUNT(*) AS INT) AS "client_count", CAST(COALESCE(substr(value, 2, 1), 'unknown') AS TEXT) AS "client_name" FROM (SELECT "id" AS "record_id" FROM "record", (SELECT "node_id", MAX("sequence_number") AS "sequence_number" FROM "record" GROUP BY "node_id") AS "max_sequence_number" WHERE ("record"."node_id" = "max_sequence_number"."node_id") AND ("record"."sequence_number" = "max_sequence_number"."sequence_number")) AS "left_table" LEFT JOIN (SELECT "record_id", "value" FROM "key_value" WHERE convert_from(key, 'UTF8') = 'c') AS "right_table" ON "left_table"."record_id" = "right_table"."record_id" GROUP BY substr(value, 2, 1)


postgresdbt2100 31m 100rows
SELECT CAST(COUNT(*) AS INT) AS "client_count", CAST(COALESCE(substr(value, 2, 1), 'unknown') AS TEXT) AS "client_name" FROM (SELECT "id" AS "record_id" FROM "record", (SELECT "node_id", MAX("sequence_number") AS "sequence_number" FROM "record" GROUP BY "node_id") AS "max_sequence_number" WHERE ("record"."node_id" = "max_sequence_number"."node_id") AND ("record"."sequence_number" = "max_sequence_number"."sequence_number")) AS "left_table" LEFT JOIN (SELECT "record_id", "value" FROM "key_value" WHERE convert_from(key, 'UTF8') = 'c') AS "right_table" ON "left_table"."record_id" = "right_table"."record_id" GROUP BY substr(value, 2, 1)


postgresdbt21000 36m 1000rows
SELECT CAST(COUNT(*) AS INT) AS "client_count", CAST(COALESCE(substr(value, 2, 1), 'unknown') AS TEXT) AS "client_name" FROM (SELECT "id" AS "record_id" FROM "record", (SELECT "node_id", MAX("sequence_number") AS "sequence_number" FROM "record" GROUP BY "node_id") AS "max_sequence_number" WHERE ("record"."node_id" = "max_sequence_number"."node_id") AND ("record"."sequence_number" = "max_sequence_number"."sequence_number")) AS "left_table" LEFT JOIN (SELECT "record_id", "value" FROM "key_value" WHERE convert_from(key, 'UTF8') = 'c') AS "right_table" ON "left_table"."record_id" = "right_table"."record_id" GROUP BY substr(value, 2, 1)


postgresdbt210000 54m 10000rows
SELECT CAST(COUNT(*) AS INT) AS "client_count", CAST(COALESCE(substr(value, 2, 1), 'unknown') AS TEXT) AS "client_name" FROM (SELECT "id" AS "record_id" FROM "record", (SELECT "node_id", MAX("sequence_number") AS "sequence_number" FROM "record" GROUP BY "node_id") AS "max_sequence_number" WHERE ("record"."node_id" = "max_sequence_number"."node_id") AND ("record"."sequence_number" = "max_sequence_number"."sequence_number")) AS "left_table" LEFT JOIN (SELECT "record_id", "value" FROM "key_value" WHERE convert_from(key, 'UTF8') = 'c') AS "right_table" ON "left_table"."record_id" = "right_table"."record_id" GROUP BY substr(value, 2, 1)


postgresdbt2100000 295m 100000rows
SELECT CAST(COUNT(*) AS INT) AS "client_count", CAST(COALESCE(substr(value, 2, 1), 'unknown') AS TEXT) AS "client_name" FROM (SELECT "id" AS "record_id" FROM "record", (SELECT "node_id", MAX("sequence_number") AS "sequence_number" FROM "record" GROUP BY "node_id") AS "max_sequence_number" WHERE ("record"."node_id" = "max_sequence_number"."node_id") AND ("record"."sequence_number" = "max_sequence_number"."sequence_number")) AS "left_table" LEFT JOIN (SELECT "record_id", "value" FROM "key_value" WHERE convert_from(key, 'UTF8') = 'c') AS "right_table" ON "left_table"."record_id" = "right_table"."record_id" GROUP BY substr(value, 2, 1)


postgresdbt21000000 1.861m 1000000rows
SELECT CAST(COUNT(*) AS INT) AS "client_count", CAST(COALESCE(substr(value, 2, 1), 'unknown') AS TEXT) AS "client_name" FROM (SELECT "id" AS "record_id" FROM "record", (SELECT "node_id", MAX("sequence_number") AS "sequence_number" FROM "record" GROUP BY "node_id") AS "max_sequence_number" WHERE ("record"."node_id" = "max_sequence_number"."node_id") AND ("record"."sequence_number" = "max_sequence_number"."sequence_number")) AS "left_table" LEFT JOIN (SELECT "record_id", "value" FROM "key_value" WHERE convert_from(key, 'UTF8') = 'c') AS "right_table" ON "left_table"."record_id" = "right_table"."record_id" GROUP BY substr(value, 2, 1)

2023-08-15 20:45 UTC, pipermerriam commented
Ok, after having some more time to think about this, I think it needs to wait for #117 to be merged, and then it should display this information based on the latest census ( and on each census' detail page).  I don't think it is accurate to display it based on the full set of known ENR records, and instead should be shown based on a single snapshot of the DHT at a given time for the information to be meaningful.

2023-09-18 01:50 UTC, KaydenML commented
Ok I updated my PR using the new Census code.

2023-09-18 06:58 UTC, KaydenML commented
Ok I updated my PR using the new Census code.

2023-09-26 20:28 UTC, mrferris commented on glados-web/templates/index.html
> +<!--        <canvas id="pieChart"></canvas>-->
Does this comment need to be deleted or uncommented?

2023-09-26 20:33 UTC, KaydenML commented on glados-web/templates/index.html
> +<!--        <canvas id="pieChart"></canvas>-->
Deleted

2023-09-26 20:33 UTC, KaydenML commented on glados-web/templates/index.html
> +<!--        <canvas id="pieChart"></canvas>-->
I believe

2023-09-26 20:55 UTC, KaydenML commented on glados-web/templates/index.html
> +<!--        <canvas id="pieChart"></canvas>-->
fixed

2023-09-26 20:59 UTC, mrferris commented on glados-web/src/routes.rs
> +    let audits_of_recent_content: Vec<AuditTuple> =
It looks like you selected the old version of this chunk instead of the new version when rebasing. This is a regression to an older commit.

2023-09-26 21:04 UTC, KaydenML commented on glados-web/src/routes.rs
> +    let audits_of_recent_content: Vec<AuditTuple> =
fixed

2023-09-27 01:20 UTC, merged