Styled-Content-dashboard-to-match-theme-of-main-page
ethereum/glados pull request #145
Opened 2023-08-01 16:40 UTC by KaydenML

I ended up styling the Content_Dashboard page to match the style of the Main Page that i had styled on my previous PR.

2023-08-10 21:05 UTC, mrferris commented on glados-web/assets/css/content_dashboard.css
> +    width: 1855px;
We need to keep everything viewable on a single page, so we don't want to use static widths for our elements.

```suggestion
    width: 100%;
```

2023-08-10 21:08 UTC, mrferris commented on glados-web/assets/css/content_dashboard.css
> +.dashboard-box2 {
Just have each div be a `.dashboard-box`, we don't need to define a class for every element that will have the same exact features.

2023-08-10 21:13 UTC, mrferris requested changes
Having some drop shadow to distinguish different dashboard components is good, though too much empty white space is being added. I would compare the spacing on the left side of and top of the page to the current spacing on glados.ethportal.net and get it close as possible to that so that we aren't regressing in terms of the page's information density.

2023-08-16 23:58 UTC, KaydenML commented
![image](https://github.com/ethereum/glados/assets/104690535/28e53c37-88a7-411d-959a-ca7c1ad26f5a)
![image](https://github.com/ethereum/glados/assets/104690535/345ed04c-d17b-4ccc-a772-cf0907eae23a)

2023-08-17 00:04 UTC, KaydenML commented
before image
![image](https://github.com/ethereum/glados/assets/104690535/2409136a-c887-4f5a-847a-8e6984635b63)

2023-08-24 05:49 UTC, mrferris requested changes
Looks great! Just a few changes/questions and this is good to go 👍

2023-08-24 05:49 UTC, mrferris commented on glados-web/templates/content_dashboard.html
> +<link rel="stylesheet" href="/static/css/content_dashboard.css">
```suggestion
    <link rel="stylesheet" href="/static/css/content_dashboard.css">
```

2023-08-24 05:49 UTC, mrferris commented on glados-web/assets/css/content_dashboard.css
> +}
Be sure to add a newline at the end of the file to avoid this error/marking

2023-08-24 05:49 UTC, mrferris commented on glados-web/templates/content_dashboard.html
> +                        </tr>
Indentation/whitespace seems to have gotten a bit off in a few spots, there are plugins/tools that do the formatting for you so you don't have to worry about it, I'd search for one in your IDE. In VSCode I have a plugin that properly formats/indents any time I save.

2023-08-24 05:49 UTC, mrferris commented on glados-web/assets/css/content_dashboard.css
> +.bootstrap-css {
Let's call this something more descriptive like `content-card`

2023-08-24 05:49 UTC, mrferris commented on glados-web/assets/css/content_dashboard.css
> +    width: 98% !important;
Not having `!important` doesn't seem to make a difference on my browser, does it on yours? I'd think it would be only be necessary if our element was being given a conflicting width

2023-08-24 05:50 UTC, mrferris commented on glados-web/assets/css/content_dashboard.css
> +}
Oh, on the main PR page it doesn't show the marking but it does on the "Files Changed" page

2023-08-24 06:04 UTC, KaydenML commented on glados-web/assets/css/content_dashboard.css
> +    width: 98% !important;
Ok thank you for giving this a review I'll work on fixing these changes, but for me I needed the important for sure for the width I will have to double check for the length though

2023-09-13 19:42 UTC, mrferris approved these changes

2023-09-13 19:42 UTC, merged