Radius chart Progress Thus Far Aiming To Complete It By Monday
ethereum/glados pull request #176
Opened 2023-10-07 18:19 UTC by KaydenML

2023-10-12 15:17 UTC, KaydenML commented
![image](https://github.com/ethereum/glados/assets/104690535/c2b362ae-4d8b-4107-a487-571cd2995758)
Picture Of The Graph Currently, Trying To Get The Labels To Look Nice And Not Overlap.

2023-10-12 15:38 UTC, KaydenML commented
![image](https://github.com/ethereum/glados/assets/104690535/78c9e47b-5461-409b-b5c3-6ee1fd3037ff)
When using a bar chart like this and displaying the data the bars appear so small that you can't even see them

![image](https://github.com/ethereum/glados/assets/104690535/45a24293-33c8-4e0a-b7b0-d729a5b65500)
But If i increase the width of the bars they overlap over each other, I could round the data up but it would give a less accurate representation of the data.

While using a density chart I was having problems displaying the data in a way that looks nice

2023-10-12 15:42 UTC, pipermerriam commented
What about:

- horizontal axis is node-id
- vertial axis is representation of radius (percentage?)

All nodes are represented on the graph as a dot?

In theory, you can then scan to see if the node-id keyspace has any weird hotspots with weird clustering of radius values and scanning the vertical axis shows normative radius values....  

I am betting that there's some manual scaling of the graph that would be needed since most of the values will be very small, and then there will be a few 100% ones that throw the scale way off.

2023-10-12 15:46 UTC, KaydenML commented
Thank you piper

2023-10-12 15:48 UTC, KaydenML commented
I'll begin looking into using this type of graph I really appreciate your time!

2023-10-12 15:49 UTC, pipermerriam commented
Feel free to move forward with this however you find to best represent it.  I would encourage you to use this "litmus test" on whether the graph is useful.

- Can we clearly see the clustering and overall distribution of node radius values of nodes in the network.

2023-10-21 20:35 UTC, KaydenML commented
![image](https://github.com/ethereum/glados/assets/104690535/1851dd22-76d3-455b-a408-dab9bbcbe7e8)

2023-10-23 19:56 UTC, KaydenML commented
@pipermerriam Hey Piper it's ready to review now

2023-10-23 20:10 UTC, pipermerriam commented on glados-web/assets/css/homepage.css
> +
Might be nice to "future" selves to add a comment to this that indicates why it is here and what it is for.  Over time, the incremental accumulation of CSS styles will grow...

2023-10-23 20:16 UTC, pipermerriam commented on glados-web/src/routes.rs
> +                .expr_as(Expr::max(Expr::col(census::Column::Id)), Alias::new("id"))
Using the auto-incrementing property of the `id` column when we have a `started_at` column that actually provides chronological ordering seems like something that might be worth the effort to do *correctly*.

I will acknowledge that the two approaches are functionally equivalent at this stage of the property, but if we were to move towards UUIDs or other identifiers in the future (which we're unlikely to do) this would break...  

So at a minimum, this might justify a comment acknowledging this situation.

2023-10-26 03:25 UTC, mrferris requested changes

2023-10-26 03:25 UTC, mrferris commented on glados-web/templates/index.html
> +    <div id="hover" style="position: absolute; opacity: 0;" ></div>
```suggestion
    <div id="hover" style="pointer-events: none; position: absolute; opacity: 0;" ></div>
```

This will fix the bug I'm seeing where a node's hover-over doesn't work if it was underneath the previous hover-over

2023-10-26 03:25 UTC, mrferris commented on glados-web/templates/index.html
> +    <div id="hover" style="position: absolute; opacity: 0;" ></div>
I would also put a bit of a background on this div, maybe a bit see-through, so that the details are easier to read

2023-10-26 03:25 UTC, mrferris commented on glados-web/assets/js/radiusdensity.js
> +// append the svg object to the body of the page
nit: indent comments in this file

2023-10-26 03:25 UTC, mrferris commented on glados-web/templates/index.html
> +            <div id="my_dataviz"></div>
make sure you change placeholders

`census-scatterplot` would be more appropriate

2023-10-26 03:25 UTC, mrferris commented on glados-web/templates/base.html
> +    <link href="/static/css/glados_pages.css" rel="stylesheet">
```suggestion
    <link href="/static/css/glados_styles.css" rel="stylesheet">
```

2023-10-26 03:25 UTC, mrferris commented on glados-web/assets/css/homepage.css
> +.card-box {
Why is `.card-box` being used by the scatterplot but not by the stats and pie chart on the same page? The card borders and everything look the same to me

2023-10-26 03:25 UTC, mrferris commented on glados-web/src/routes.rs
> +#[derive(FromQueryResult, Serialize, Debug)]
It doesn't seem like this needs the `FromQueryResult` trait

2023-10-26 03:25 UTC, mrferris commented on glados-web/src/routes.rs
> +#[derive(FromQueryResult, Serialize, Debug)]
It doesn't seem like this needs the `FromQueryResult` trait

2023-10-26 03:25 UTC, mrferris commented on glados-web/src/routes.rs
> +    let mut average_radius = Query::select();
this entire thing should also be wrapped in a function that returns a `Vec<CalculatedRadiusChartData>` that is called inside of the main `root` function instead of being inline

2023-10-26 03:25 UTC, mrferris commented on glados-web/src/routes.rs
> +                .expr_as(Expr::max(Expr::col(census::Column::Id)), Alias::new("id"))
Yea I think doing it based off `started_at` is better in principle

2023-10-30 07:03 UTC, KaydenML commented
https://github.com/ethereum/glados/pull/180 
kolby's code in this PR and his usage of started_at was a really big help in fixing this change.

2023-10-31 18:35 UTC, mrferris commented on glados-web/src/routes.rs
> +            Expr::col(census_node::Column::DataRadius),
for posterity: kayden pointed out that this approach won't allow the entire node ID to be displayable

2023-11-01 19:27 UTC, mrferris approved these changes

2023-11-01 19:27 UTC, merged