feat: implement "Initial state-root based auditing strategy for state network"
ethereum/glados pull request #259
Opened 2024-05-10 00:16 UTC by KolbyML

2024-05-17 14:39 UTC, mrferris commented on glados-audit/src/state.rs
> +        "state_itermidate_trie_node",
```suggestion
        "state_intermediate_trie_node",
```

2024-05-17 18:56 UTC, KolbyML commented
@mrferris I fixed the spelling issue, is there any other concerns with this PR?

2024-05-17 22:06 UTC, mrferris requested changes

2024-05-18 05:03 UTC, KolbyML commented
@mrferris I believe I resolved the PR concerns, let me know if you have any other concerns

2024-05-18 11:41 UTC, morph-dev requested changes
Since I'm not familiar with glados codebase, I focused mostly on code in `glados-audit/src/state.rs`.

2024-05-18 11:41 UTC, morph-dev commented on glados-audit/src/state.rs
> +) -> Result<Option<(StateContentKey, usize)>, (anyhow::Error, StateContentKey)> {
What is `usize` in the return type supposed to be?
Why is it `0` for extension node and `index` for branch node? This doesn't seem correct.

2024-05-18 11:41 UTC, morph-dev commented on glados-audit/src/state.rs
> +    let mut stack = vec![StateContentKey::AccountTrieNode(AccountTrieNodeKey {
Why is this stack? We always have at most one element in, right?

2024-05-18 15:25 UTC, KolbyML commented on glados-audit/src/lib.rs
> +    if config.history {
I think that should wait till a future PR, till we know what we want to do with beacon

2024-05-18 15:27 UTC, KolbyML commented on entity/src/state_roots.rs
> +    #[sea_orm(primary_key)]
sure I don't think it will make a difference but might as well

2024-05-18 15:29 UTC, KolbyML commented on glados-audit/src/state.rs
> +                    Err((anyhow!(
I am aware of this, but since I am not dealing with the contract storage trie, I decided that could be done in a future PR, when we walk the contract storage trie

2024-05-18 15:29 UTC, KolbyML commented on glados-audit/src/state.rs
> +                            path: Nibbles::try_from_unpacked_nibbles(path).expect("Bug building path in random_state_walk"),
good catch

2024-05-18 15:40 UTC, KolbyML commented on glados-audit/src/state.rs
> +    let mut stack = vec![StateContentKey::AccountTrieNode(AccountTrieNodeKey {
Because I was originally writing this to walk a whole tree and DFS uses a stack, I thought I would leave it as it doesn't break anything, but it can also be useful for the future

2024-05-18 15:53 UTC, KolbyML commented on glados-audit/src/state.rs
> +) -> Result<Option<(StateContentKey, usize)>, (anyhow::Error, StateContentKey)> {
I updated the return of extension node. I am returning the next bit of the path to continue the walk

2024-05-18 16:07 UTC, KolbyML commented
@morph-dev let know if you have any other concerns, ready for another review

2024-05-19 11:46 UTC, morph-dev requested changes

2024-05-19 11:46 UTC, morph-dev commented on glados-audit/src/lib.rs
> +    if config.history {
My philosophy is that *"if you touch the code, you should leave it in a better state than you find it"*. This applies to code readability, code design, and test. This greatly helps with technical debt, but it does sacrifice development speed (at least for the short term).

This is just my opinion and I don't want to enforce it. So it's fine if you just acknowledge it.

2024-05-19 11:46 UTC, morph-dev commented on glados-audit/src/state.rs
> +                        let trie_node = encoded_trie_node.node.as_trie_node().expect("Trie node received from the portal network should be decoded as a trie node");
I'm not sure if this is normally done, but should we check whether retrieved value (in this case trie node) actually matches the content_key?
In this case, I would say it's enough to check that `EncodedTrieNode.node_hash` matches the `node_hash` from content key.

2024-05-19 11:46 UTC, morph-dev commented on glados-audit/src/state.rs
> +        StateContentKey::AccountTrieNode(AccountTrieNodeKey {
Is this supposed to be the same content key as the one created at line 178? If so, maybe save it in a variable: `root_content_key`?

2024-05-19 11:46 UTC, morph-dev commented on glados-audit/src/state.rs
> +            if let Err((err, content_key)) = random_state_walk(
I feel like `save_state_audit` should be called here, both in case of error (as it is now) and for success (not inside `process_trie_node`).

2024-05-19 16:04 UTC, KolbyML commented on glados-audit/src/state.rs
> +                } => match content_value {
Very cool I didn't think of doing it like this

2024-05-19 16:39 UTC, KolbyML commented on glados-audit/src/state.rs
> +    let mut stack = vec![StateContentKey::AccountTrieNode(AccountTrieNodeKey {
Fine it isn't a big deal as if we need it we can always change it back

2024-05-19 17:02 UTC, KolbyML commented on glados-audit/src/lib.rs
> +    if config.history {
I am not sure the proper way to acknowledge this but I did read it.

I would want to wait till the next PR for beacon audit strategies to be done for a refactor to be done. As combining them creates more work and complexity to handle for whenever a beacon audit refactor happens,

I implemented what was suggested cause it isn't the biggest concern on earth, but I do think this is less clean and more complex. I don't think less code duplication is worth that cost in this example

2024-05-19 17:04 UTC, KolbyML commented
@morph-dev ready for another round, I believe I resolved all of the concerns but as always if I missed any please let me know.

2024-05-20 13:05 UTC, morph-dev requested changes
Almost there. One important comment and two nits.

2024-05-20 13:05 UTC, morph-dev commented on glados-audit/src/state.rs
> +) -> Result<(AccountTrieNodeKey, bool), (anyhow::Error, AccountTrieNodeKey)> {
nit: This feels like an abuse of `Result` type. Knowing you are going to keep refactoring this as we add support for storage trie, I would say it's good for now. But return type could be something like this:
```rust
enum ProcessAccountTrieNodeResult {
  LeafReached,
  NextNode(AccountTrieNodeKey),
  Error(String), // or if you really want Error(anyhow::Error)
}
```

Maybe also pass `EncodedTrieNode` (instead of `Node`) and do other two checks here as well.

2024-05-20 21:54 UTC, KolbyML commented on glados-audit/src/state.rs
> +        let content_value = match StateNetworkApiClient::recursive_find_content(
updated, didn't notice it

2024-05-20 21:59 UTC, KolbyML commented on glados-audit/src/state.rs
> +) -> Result<(AccountTrieNodeKey, bool), (anyhow::Error, AccountTrieNodeKey)> {
> nit: This feels like an abuse of `Result` type. Knowing you are going to keep refactoring this as we add support for storage trie, I would say it's good for now. But return type could be something like this:
> 
> ```rust
> enum ProcessAccountTrieNodeResult {
>   LeafReached,
>   NextNode(AccountTrieNodeKey),
>   Error(String), // or if you really want Error(anyhow::Error)
> }
> ```


I think it is a good idea, I would be happy to do this in a future PR when we refactor this for the storage trie like you said

2024-05-21 11:20 UTC, morph-dev approved these changes
LGTM, but wait for approval from @mrferris as well (since I'm not familiar with glados codebase and I mostly focused on the state related code).

2024-05-21 18:13 UTC, mrferris approved these changes

2024-05-21 20:13 UTC, merged