refactor: updated glados to use ethportal-api instead of custom json-rpc code
ethereum/glados pull request #287
Opened 2024-06-25 15:40 UTC by KolbyML

2024-06-26 04:27 UTC, mrferris requested changes

2024-06-26 04:27 UTC, mrferris commented on glados-core/src/jsonrpc.rs
> -            },
This logic was removed, which is making audits run without ever being labelled a success or failure because the error (defined in the Portal RPC spec) propagates and makes it appear that the audit itself errored.

2024-06-26 04:54 UTC, KolbyML commented on glados-core/src/jsonrpc.rs
> -            },
Ok I added that back if you could give it another look now

2024-06-26 14:43 UTC, mrferris requested changes

2024-06-26 14:43 UTC, mrferris commented on glados-core/src/jsonrpc.rs
> +                .await?;
`get_content_with_trace` looks great, but `get_content` is returning the error rather than checking whether it's a `ContentNotFound` error. Should do the same as `get_content_with_trace`.

2024-06-26 15:05 UTC, KolbyML commented on glados-core/src/jsonrpc.rs
> +                .await?;
Ready for another look 🫡

2024-06-26 18:34 UTC, mrferris approved these changes
⭐️

2024-06-27 03:02 UTC, KolbyML commented
Thank you for the review @mrferris I really appreciate it

2024-06-27 03:03 UTC, merged